- include_tasks: setup-debian.yml
  when: ansible_os_family|lower == 'debian'

- include_tasks: setup-redhat.yml
  when: ansible_os_family|lower == 'redhat'

# As of 12/2022, get-pip only supports python>=3.7
- name: download get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
  when: python_base_version != '3.6'

- name: download get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/pip/3.6/get-pip.py
    dest: /tmp/get-pip.py
  when: python_base_version == '3.6'

- name: "install pip{{ python_base_version }}"
  become: true
  become_user: "{{ root_user }}"
  command: /usr/bin/python{{ python_base_version }} /tmp/get-pip.py
  args:
    creates: /usr/local/bin/pip{{ python_base_version }}

- name: "create virtual environment: {{ python_venv_path }}"
  when: python_venv_path is truthy
  pip:
    virtualenv: "{{ python_venv_path }}"
    virtualenv_command: /usr/bin/python{{ python_base_version }} -m venv
    name: "{{ python_venv_packages }}"
    state: "{{ python_venv_state }}"
