- name: Install python{{ python_base_version }}
  become: true
  become_user: "{{ root_user }}"
  yum:
    update_cache: true
    name:
    - python{{ python_base_version | replace('.', '') }}
    - wget

- name: Install Tk GUI toolkit for python3
  when: python_install_tk|bool
  become: true
  become_user: "{{ root_user }}"
  yum:
    name:
    - python3-tkinter  # TODO this may not be correct
