- name: Install python{{ python_base_version }}
  become: true
  become_user: "{{ root_user }}"
  yum:
    update_cache: true
    name:
    - python{{ python_base_version | replace('.', '') }}
    - wget
