- name: Converge
  hosts: all

  pre_tasks:
  - name: Update apt cache.
    become: true
    apt:
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_os_family == 'Debian'

  vars:
  - run_tests: true
  - ansible_python_interpreter: /usr/bin/python3

  roles:
  - role: "marvel-nccr.python"
